import { FIXTURE_LIBRARY } from './fixture-library.js';
import { ACCESSORY_LIBRARY } from './accessory-library.js';
import { ADDITIONAL_ACCESSORY_LIBRARY } from './additional-accessory-library.js';
import { SPOTLIGHT_ACCESSORY_LIBRARY } from './spotlight-accessory-library.js';
import { SPACE_LIGHT_ACCESSORY_LIBRARY } from './space-light-accessory-library.js';
import { STORM_80C_ADAPTED_ACCESSORY_LIBRARY } from './storm-80c-adapted-accessory-library.js';
import { APUTURE_MOUNT_SYSTEM_LIBRARY } from './aputure-mount-system-library.js';
import { STORM_SUPPORT_CONTROL_LIBRARY } from './storm-support-control-library.js';
import { ELECTRO_STORM_TRANSPORT_POWER_LIBRARY } from './electro-storm-transport-power-library.js';
import { ELECTRO_STORM_SYSTEM_ACCESSORY_LIBRARY } from './electro-storm-system-accessory-library.js';
import { ARRI_SKYPANEL_X_FIXTURES, ARRI_SKYPANEL_X_ACCESSORIES } from './arri-skypanel-x-library.js';
import { ARRI_SKYPANEL_PRO_FIXTURES, ARRI_SKYPANEL_PRO_ACCESSORIES } from './arri-skypanel-pro-library.js';
import { ARRI_SKYPANEL_CLASSIC_S30_FIXTURES, ARRI_SKYPANEL_CLASSIC_S30_ACCESSORIES } from './arri-skypanel-classic-s30-library.js';
import { ARRI_SKYPANEL_CLASSIC_S60_FIXTURES, ARRI_SKYPANEL_CLASSIC_S60_ACCESSORIES } from './arri-skypanel-classic-s60-library.js';
import { ARRI_SKYPANEL_CLASSIC_S120_FIXTURES, ARRI_SKYPANEL_CLASSIC_S120_ACCESSORIES } from './arri-skypanel-classic-s120-library.js';
import { ARRI_SKYPANEL_CLASSIC_S360_FIXTURES, ARRI_SKYPANEL_CLASSIC_S360_ACCESSORIES } from './arri-skypanel-classic-s360-library.js';
import { ARRI_SKYPANEL_KITS } from './arri-skypanel-kits-library.js';
import { ARRI_SKYPANEL_DISCONTINUED_FIXTURES, ARRI_SKYPANEL_DISCONTINUED_ACCESSORIES } from './arri-skypanel-discontinued-library.js';
import { ARRI_L_SERIES_PLUS_FIXTURES, ARRI_L_SERIES_PLUS_ACCESSORIES } from './arri-l-series-plus-library.js';
import { ARRI_ORBITER_FIXTURES, ARRI_ORBITER_ACCESSORIES } from './arri-orbiter-library.js';
import { ARRI_L_SERIES_C_DISCONTINUED_FIXTURES, ARRI_L_SERIES_C_DISCONTINUED_ACCESSORIES } from './arri-l-series-c-discontinued-library.js';
import { ARRI_L_SERIES_DT_TT_DISCONTINUED_FIXTURES, ARRI_L_SERIES_DT_TT_DISCONTINUED_ACCESSORIES } from './arri-l-series-dt-tt-discontinued-library.js';
import { ARRI_CASTER_SERIES_DISCONTINUED_FIXTURES, ARRI_CASTER_SERIES_DISCONTINUED_ACCESSORIES } from './arri-caster-series-discontinued-library.js';
import { ARRI_M_SERIES_M8_FIXTURES, ARRI_M_SERIES_M8_ACCESSORIES } from './arri-m-series-m8-library.js';
import { ARRI_M_SERIES_M18_FIXTURES, ARRI_M_SERIES_M18_ACCESSORIES } from './arri-m-series-m18-library.js';
import { ARRI_M_SERIES_M40_FIXTURES, ARRI_M_SERIES_M40_ACCESSORIES } from './arri-m-series-m40-library.js';
import { ARRI_M_SERIES_M90_FIXTURES, ARRI_M_SERIES_M90_ACCESSORIES } from './arri-m-series-m90-library.js';
import { ARRI_M_SERIES_ARRIMAX_18_12_FIXTURES, ARRI_M_SERIES_ARRIMAX_18_12_ACCESSORIES } from './arri-m-series-arrimax-18-12-library.js';
import { ARRI_TRUE_BLUE_D5_FIXTURES, ARRI_TRUE_BLUE_D5_ACCESSORIES } from './arri-true-blue-d5-library.js';
import { ARRI_TRUE_BLUE_D12_FIXTURES, ARRI_TRUE_BLUE_D12_ACCESSORIES } from './arri-true-blue-d12-library.js';
import { ARRI_TRUE_BLUE_D25_FIXTURES, ARRI_TRUE_BLUE_D25_ACCESSORIES } from './arri-true-blue-d25-library.js';
import { ARRI_TRUE_BLUE_D40_FIXTURES, ARRI_TRUE_BLUE_D40_ACCESSORIES } from './arri-true-blue-d40-library.js';
import { ARRI_DAYLIGHT_18_12_FIXTURES, ARRI_DAYLIGHT_18_12_ACCESSORIES } from './arri-daylight-18-12-library.js';
import { ARRI_ARRISUN_DISCONTINUED_FIXTURES, ARRI_ARRISUN_DISCONTINUED_ACCESSORIES } from './arri-daylight-discontinued-arrisun-library.js';
import { ARRI_ARRISUN_EVENT_DISCONTINUED_FIXTURES, ARRI_ARRISUN_EVENT_DISCONTINUED_ACCESSORIES } from './arri-arrisun-event-discontinued-library.js';
import { ARRI_COMPACT_THEATER_DISCONTINUED_FIXTURES, ARRI_COMPACT_THEATER_DISCONTINUED_ACCESSORIES } from './arri-compact-theater-discontinued-library.js';
import { ARRI_COMPACT_DISCONTINUED_FIXTURES, ARRI_COMPACT_DISCONTINUED_ACCESSORIES } from './arri-compact-discontinued-library.js';
import { ARRI_ARRILUX_DISCONTINUED_FIXTURES, ARRI_ARRILUX_DISCONTINUED_ACCESSORIES } from './arri-arrilux-discontinued-library.js';
import { ARRI_X_SERIES_DISCONTINUED_FIXTURES, ARRI_X_SERIES_DISCONTINUED_ACCESSORIES } from './arri-x-series-discontinued-library.js';
import { ARRI_ARRILITE_PLUS_FIXTURES, ARRI_ARRILITE_PLUS_ACCESSORIES } from './arri-arrilite-plus-library.js';
import { ARRI_JUNIOR_FIXTURES, ARRI_JUNIOR_ACCESSORIES } from './arri-junior-library.js';
import { ARRI_TRUE_BLUE_T1_FIXTURES, ARRI_TRUE_BLUE_T1_ACCESSORIES } from './arri-true-blue-t1-library.js';
import { ARRI_TRUE_BLUE_T2_FIXTURES, ARRI_TRUE_BLUE_T2_ACCESSORIES } from './arri-true-blue-t2-library.js';
import { ARRI_TRUE_BLUE_T5_FIXTURES, ARRI_TRUE_BLUE_T5_ACCESSORIES } from './arri-true-blue-t5-library.js';
import { ARRI_TRUE_BLUE_ST1_FIXTURES, ARRI_TRUE_BLUE_ST1_ACCESSORIES } from './arri-true-blue-st1-library.js';
import { ARRI_TRUE_BLUE_ST2_3_FIXTURES, ARRI_TRUE_BLUE_ST2_3_ACCESSORIES } from './arri-true-blue-st2-3-library.js';
import { ARRI_TRUE_BLUE_ST5_FIXTURES, ARRI_TRUE_BLUE_ST5_ACCESSORIES } from './arri-true-blue-st5-library.js';
import { ARRI_TRUE_BLUE_ST_THEATER_FIXTURES, ARRI_TRUE_BLUE_ST_THEATER_ACCESSORIES } from './arri-true-blue-st-theater-library.js';
import { ARRI_STUDIO_T_FIXTURES, ARRI_STUDIO_T_ACCESSORIES } from './arri-studio-t-library.js';
import { ARRI_TUNGSTEN_DISCONTINUED_FIXTURES, ARRI_TUNGSTEN_DISCONTINUED_ACCESSORIES } from './arri-tungsten-discontinued-library.js';
import { ARRI_TUNGSTEN_KITS } from './arri-tungsten-kits-library.js';
import { ASTERA_TITANTUBE_FIXTURES, ASTERA_TITANTUBE_ACCESSORIES } from './astera-titantube-library.js';
import { ASTERA_HELIOSTUBE_FIXTURES, ASTERA_HELIOSTUBE_ACCESSORIES } from './astera-heliostube-library.js';
import { ASTERA_HYPERIONTUBE_FIXTURES, ASTERA_HYPERIONTUBE_ACCESSORIES } from './astera-hyperiontube-library.js';
import { ASTERA_HYDRAPANEL_FIXTURES, ASTERA_HYDRAPANEL_ACCESSORIES } from './astera-hydrapanel-library.js';
import { ASTERA_AX9_POWERPAR_FIXTURES, ASTERA_AX9_POWERPAR_ACCESSORIES } from './astera-ax9-powerpar-library.js';
import { ASTERA_PIXELBRICK_FIXTURES, ASTERA_PIXELBRICK_ACCESSORIES } from './astera-pixelbrick-library.js';
import { ASTERA_AX5_TRIPLEPAR_FIXTURES, ASTERA_AX5_TRIPLEPAR_ACCESSORIES } from './astera-ax5-triplepar-library.js';
import { ASTERA_AX2_PIXELBAR_FIXTURES, ASTERA_AX2_PIXELBAR_ACCESSORIES } from './astera-ax2-pixelbar-library.js';
import { ASTERA_NYX_BULB_FIXTURES, ASTERA_NYX_BULB_ACCESSORIES } from './astera-nyx-bulb-library.js';
import { ASTERA_PLUTOFRESNEL_FIXTURES, ASTERA_PLUTOFRESNEL_ACCESSORIES } from './astera-plutofresnel-library.js';
import { ASTERA_LEOFRESNEL_FIXTURES, ASTERA_LEOFRESNEL_ACCESSORIES } from './astera-leofresnel-library.js';
import { ASTERA_QUIKSPOT_FIXTURES, ASTERA_QUIKSPOT_ACCESSORIES } from './astera-quikspot-library.js';
import { ASTERA_LUNABULB_FIXTURES, ASTERA_LUNABULB_ACCESSORIES } from './astera-lunabulb-library.js';
import { ASTERA_QUIKBEAM_FIXTURES, ASTERA_QUIKBEAM_ACCESSORIES } from './astera-quikbeam-library.js';
import { ASTERA_QUIKPUNCH_FIXTURES, ASTERA_QUIKPUNCH_ACCESSORIES } from './astera-quikpunch-library.js';
import { ASTERA_AX3_LIGHTDROP_FIXTURES, ASTERA_AX3_LIGHTDROP_ACCESSORIES } from './astera-ax3-lightdrop-library.js';
import { ASTERA_SOLABULB_FIXTURES, ASTERA_SOLABULB_ACCESSORIES } from './astera-solabulb-library.js';
import { ASTERA_AX1_PIXELTUBE_FIXTURES, ASTERA_AX1_PIXELTUBE_ACCESSORIES } from './astera-ax1-pixeltube-library.js';
import { ASTERA_AX7_SPOTLITE_FIXTURES, ASTERA_AX7_SPOTLITE_ACCESSORIES } from './astera-ax7-spotlite-library.js';
import { ASTERA_AX10_SPOTMAX_FIXTURES, ASTERA_AX10_SPOTMAX_ACCESSORIES } from './astera-ax10-spotmax-library.js';
import { DESISTI_SUPER_LED_F47_FIXTURES, DESISTI_SUPER_LED_F47_ACCESSORIES } from './desisti-super-led-f47-library.js';
import { DESISTI_LED_FRESNEL_FIXTURES, DESISTI_LED_FRESNEL_ACCESSORIES } from './desisti-led-fresnel-series-library.js';
import { DESISTI_PICCOLETTO_FIXTURES, DESISTI_PICCOLETTO_ACCESSORIES } from './desisti-piccoletto-library.js';
import { DESISTI_SOFTLED_FIXTURES, DESISTI_SOFTLED_ACCESSORIES } from './desisti-softled-library.js';
import { DESISTI_GIOTTO_LED_FIXTURES, DESISTI_GIOTTO_LED_ACCESSORIES } from './desisti-giotto-led-library.js';
import { DESISTI_GALILEO_FIXTURES, DESISTI_GALILEO_ACCESSORIES } from './desisti-galileo-softnel-library.js';
import { DESISTI_SPACELIGHT_FIXTURES, DESISTI_SPACELIGHT_ACCESSORIES } from './desisti-spacelight-library.js';
import { DESISTI_LITE_FIXTURES, DESISTI_LITE_ACCESSORIES } from './desisti-lite-series-library.js';
import { DESISTI_SOFTLED_VWC_FIXTURES, DESISTI_SOFTLED_VWC_ACCESSORIES } from './desisti-softled-vwc-library.js';
import { DESISTI_MUSES_FIXTURES, DESISTI_MUSES_ACCESSORIES } from './desisti-muses-library.js';
import { DESISTI_TUNGSTEN_FIXTURES, DESISTI_TUNGSTEN_ACCESSORIES } from './desisti-tungsten-library.js';
import { DESISTI_TUNGSTEN_SOFT_BROAD_FIXTURES, DESISTI_TUNGSTEN_SOFT_BROAD_ACCESSORIES } from './desisti-tungsten-soft-broad-library.js';
import { DESISTI_HMI_FIXTURES, DESISTI_HMI_ACCESSORIES } from './desisti-hmi-library.js';
import { DESISTI_CONVENTIONAL_EXTRA_FIXTURES, DESISTI_CONVENTIONAL_EXTRA_ACCESSORIES } from './desisti-conventional-extra-library.js';
import { GODOX_CONTINUOUS_FIXTURES, GODOX_CONTINUOUS_ACCESSORIES } from './godox-continuous-library.js';
import { ALADDIN_MOSAIC_FIXTURES, ALADDIN_MOSAIC_ACCESSORIES } from './aladdin-mosaic-library.js';
import { ALADDIN_FABRIC_LITE_FIXTURES, ALADDIN_FABRIC_LITE_ACCESSORIES } from './aladdin-fabric-lite-library.js';
import { ALADDIN_BI_FLEX_FIXTURES, ALADDIN_BI_FLEX_ACCESSORIES } from './aladdin-bi-flex-library.js';
import { ALADDIN_ALL_IN_FIXTURES, ALADDIN_ALL_IN_ACCESSORIES } from './aladdin-all-in-library.js';
import { ALADDIN_BASE_LITE_FIXTURES, ALADDIN_BASE_LITE_ACCESSORIES } from './aladdin-base-lite-library.js';
import { ALADDIN_ONBOARD_FIXTURES, ALADDIN_ONBOARD_ACCESSORIES } from './aladdin-onboard-library.js';
import { ALADDIN_BI_FABRIC_FIXTURES, ALADDIN_BI_FABRIC_ACCESSORIES } from './aladdin-bi-fabric-library.js';
import { LITEGEAR_LITEMAT_SPECTRUM_G2_FIXTURES, LITEGEAR_LITEMAT_SPECTRUM_G2_ACCESSORIES } from './litegear-litemat-spectrum-g2-library.js';
import { LITEGEAR_LITEMAT_PLUS_FIXTURES, LITEGEAR_LITEMAT_PLUS_ACCESSORIES } from './litegear-litemat-plus-library.js';
import { LITEGEAR_LITEMAT_SPECTRUM_2019_FIXTURES, LITEGEAR_LITEMAT_SPECTRUM_2019_ACCESSORIES } from './litegear-litemat-spectrum-2019-library.js';
import { LITEGEAR_LITEMAT_S2_FIXTURES, LITEGEAR_LITEMAT_S2_ACCESSORIES } from './litegear-litemat-s2-library.js';
import { EVLIGHT_GEM_GEMX_FIXTURES, EVLIGHT_GEM_GEMX_ACCESSORIES } from './evlight-gem-gemx-library.js';
import { EVLIGHT_FRESNEL_FIXTURES, EVLIGHT_FRESNEL_ACCESSORIES } from './evlight-fresnel-library.js';
import { EVLIGHT_GEMX_HARD_FIXTURES, EVLIGHT_GEMX_HARD_ACCESSORIES } from './evlight-gemx-hard-library.js';
import { EVLIGHT_PROFILE_FIXTURES, EVLIGHT_PROFILE_ACCESSORIES } from './evlight-profile-library.js';
import { EVLIGHT_GEMX_LARGE_FIXTURES, EVLIGHT_GEMX_LARGE_ACCESSORIES } from './evlight-gemx-large-library.js';
import { KINOFLO_CURRENT_FIXTURES, KINOFLO_CURRENT_ACCESSORIES } from './kinoflo-current-library.js';
import { KINOFLO_FREESTYLE_AIR_FIXTURES, KINOFLO_FREESTYLE_AIR_ACCESSORIES } from './kinoflo-freestyle-air-library.js';
import { KINOFLO_CELEB_LED_FIXTURES, KINOFLO_CELEB_LED_ACCESSORIES } from './kinoflo-celeb-led-library.js';
import { KINOFLO_DIVA_LITE_LED_FIXTURES, KINOFLO_DIVA_LITE_LED_ACCESSORIES } from './kinoflo-diva-lite-led-library.js';
import { KINOFLO_IMAGE_SELECT_FIXTURES, KINOFLO_IMAGE_SELECT_ACCESSORIES } from './kinoflo-image-select-led-library.js';
import { KINOFLO_4BANK_TEGRA_FIXTURES, KINOFLO_4BANK_TEGRA_ACCESSORIES } from './kinoflo-4bank-tegra-library.js';
import { KINOFLO_PARABEAM_PARAZIP_FIXTURES, KINOFLO_PARABEAM_PARAZIP_ACCESSORIES } from './kinoflo-parabeam-parazip-library.js';
import { KINOFLO_VISTABEAM_WALLO_FIXTURES, KINOFLO_VISTABEAM_WALLO_ACCESSORIES } from './kinoflo-vistabeam-wallolite-library.js';
import { KINOFLO_DIVA_BARFLY_FIXTURES, KINOFLO_DIVA_BARFLY_ACCESSORIES } from './kinoflo-diva-barfly-library.js';
import { KINOFLO_IMARA_FIXTURES, KINOFLO_IMARA_ACCESSORIES } from './kinoflo-imara-library.js';
import { applyAccessoryCompatibilityOverrides } from './accessory-compatibility-overrides.js';
import { applyCatalogCompatibilityCorrections } from './catalog-compatibility-corrections.js';
import { applyElectroStormCanonicalCorrections } from './electro-storm-canonical-corrections.js';

function clone(value) { return JSON.parse(JSON.stringify(value)); }
function unique(values = []) { return [...new Set(values)]; }
function mergeAccessory(base, extra) {
  const merged = { ...base, ...extra };
  merged.compatibleWith = unique([...(base.compatibleWith || []), ...(extra.compatibleWith || [])]);
  merged.compatibility = { ...(base.compatibility || {}), ...(extra.compatibility || {}) };
  for (const key of ['manufacturer','model','category','mount','effectOnLight','sourceUrl']) if (base[key] != null) merged[key] = base[key];
  if (base.includedWithFixture != null) merged.includedWithFixture = base.includedWithFixture;
  return merged;
}

export function buildRuntimeCatalog() {
  const fixtures = [...clone(FIXTURE_LIBRARY), ...clone(ARRI_SKYPANEL_X_FIXTURES), ...clone(ARRI_SKYPANEL_PRO_FIXTURES), ...clone(ARRI_SKYPANEL_CLASSIC_S30_FIXTURES), ...clone(ARRI_SKYPANEL_CLASSIC_S60_FIXTURES), ...clone(ARRI_SKYPANEL_CLASSIC_S120_FIXTURES), ...clone(ARRI_SKYPANEL_CLASSIC_S360_FIXTURES), ...clone(ARRI_SKYPANEL_DISCONTINUED_FIXTURES), ...clone(ARRI_L_SERIES_PLUS_FIXTURES), ...clone(ARRI_ORBITER_FIXTURES), ...clone(ARRI_L_SERIES_C_DISCONTINUED_FIXTURES), ...clone(ARRI_L_SERIES_DT_TT_DISCONTINUED_FIXTURES), ...clone(ARRI_CASTER_SERIES_DISCONTINUED_FIXTURES), ...clone(ARRI_M_SERIES_M8_FIXTURES), ...clone(ARRI_M_SERIES_M18_FIXTURES), ...clone(ARRI_M_SERIES_M40_FIXTURES), ...clone(ARRI_M_SERIES_M90_FIXTURES), ...clone(ARRI_M_SERIES_ARRIMAX_18_12_FIXTURES), ...clone(ARRI_TRUE_BLUE_D5_FIXTURES), ...clone(ARRI_TRUE_BLUE_D12_FIXTURES), ...clone(ARRI_TRUE_BLUE_D25_FIXTURES), ...clone(ARRI_TRUE_BLUE_D40_FIXTURES), ...clone(ARRI_DAYLIGHT_18_12_FIXTURES), ...clone(ARRI_ARRISUN_DISCONTINUED_FIXTURES), ...clone(ARRI_ARRISUN_EVENT_DISCONTINUED_FIXTURES), ...clone(ARRI_COMPACT_THEATER_DISCONTINUED_FIXTURES), ...clone(ARRI_COMPACT_DISCONTINUED_FIXTURES), ...clone(ARRI_ARRILUX_DISCONTINUED_FIXTURES), ...clone(ARRI_X_SERIES_DISCONTINUED_FIXTURES), ...clone(ARRI_ARRILITE_PLUS_FIXTURES), ...clone(ARRI_JUNIOR_FIXTURES), ...clone(ARRI_TRUE_BLUE_T1_FIXTURES), ...clone(ARRI_TRUE_BLUE_T2_FIXTURES), ...clone(ARRI_TRUE_BLUE_T5_FIXTURES), ...clone(ARRI_TRUE_BLUE_ST1_FIXTURES), ...clone(ARRI_TRUE_BLUE_ST2_3_FIXTURES), ...clone(ARRI_TRUE_BLUE_ST5_FIXTURES), ...clone(ARRI_TRUE_BLUE_ST_THEATER_FIXTURES), ...clone(ARRI_STUDIO_T_FIXTURES), ...clone(ARRI_TUNGSTEN_DISCONTINUED_FIXTURES)];
  fixtures.push(...clone(ASTERA_TITANTUBE_FIXTURES));
  fixtures.push(...clone(ASTERA_HELIOSTUBE_FIXTURES));
  fixtures.push(...clone(ASTERA_HYPERIONTUBE_FIXTURES));
  fixtures.push(...clone(ASTERA_HYDRAPANEL_FIXTURES));
  fixtures.push(...clone(ASTERA_AX9_POWERPAR_FIXTURES));
  fixtures.push(...clone(ASTERA_PIXELBRICK_FIXTURES));
  fixtures.push(...clone(ASTERA_AX5_TRIPLEPAR_FIXTURES));
  fixtures.push(...clone(ASTERA_AX2_PIXELBAR_FIXTURES));
  fixtures.push(...clone(ASTERA_NYX_BULB_FIXTURES));
  fixtures.push(...clone(ASTERA_PLUTOFRESNEL_FIXTURES));
  fixtures.push(...clone(ASTERA_LEOFRESNEL_FIXTURES));
  fixtures.push(...clone(ASTERA_QUIKSPOT_FIXTURES));
  fixtures.push(...clone(ASTERA_LUNABULB_FIXTURES));
  fixtures.push(...clone(ASTERA_QUIKBEAM_FIXTURES));
  fixtures.push(...clone(ASTERA_QUIKPUNCH_FIXTURES));
  fixtures.push(...clone(ASTERA_AX3_LIGHTDROP_FIXTURES));
  fixtures.push(...clone(ASTERA_SOLABULB_FIXTURES));
  fixtures.push(...clone(ASTERA_AX1_PIXELTUBE_FIXTURES));
  fixtures.push(...clone(ASTERA_AX7_SPOTLITE_FIXTURES));
  fixtures.push(...clone(ASTERA_AX10_SPOTMAX_FIXTURES));
  fixtures.push(...clone(DESISTI_SUPER_LED_F47_FIXTURES));
  fixtures.push(...clone(DESISTI_LED_FRESNEL_FIXTURES));
  fixtures.push(...clone(DESISTI_PICCOLETTO_FIXTURES));
  fixtures.push(...clone(DESISTI_SOFTLED_FIXTURES));
  fixtures.push(...clone(DESISTI_GIOTTO_LED_FIXTURES));
  fixtures.push(...clone(DESISTI_GALILEO_FIXTURES));
  fixtures.push(...clone(DESISTI_SPACELIGHT_FIXTURES));
  fixtures.push(...clone(DESISTI_LITE_FIXTURES));
  fixtures.push(...clone(DESISTI_SOFTLED_VWC_FIXTURES));
  fixtures.push(...clone(DESISTI_MUSES_FIXTURES));
  fixtures.push(...clone(DESISTI_TUNGSTEN_FIXTURES));
  fixtures.push(...clone(DESISTI_TUNGSTEN_SOFT_BROAD_FIXTURES));
  fixtures.push(...clone(DESISTI_HMI_FIXTURES));
  fixtures.push(...clone(DESISTI_CONVENTIONAL_EXTRA_FIXTURES));
  fixtures.push(...clone(GODOX_CONTINUOUS_FIXTURES));
  fixtures.push(...clone(ALADDIN_MOSAIC_FIXTURES));
  fixtures.push(...clone(ALADDIN_FABRIC_LITE_FIXTURES));
  fixtures.push(...clone(ALADDIN_BI_FLEX_FIXTURES));
  fixtures.push(...clone(ALADDIN_ALL_IN_FIXTURES));
  fixtures.push(...clone(ALADDIN_BASE_LITE_FIXTURES));
  fixtures.push(...clone(ALADDIN_ONBOARD_FIXTURES));
  fixtures.push(...clone(ALADDIN_BI_FABRIC_FIXTURES));
  fixtures.push(...clone(LITEGEAR_LITEMAT_SPECTRUM_G2_FIXTURES));
  fixtures.push(...clone(LITEGEAR_LITEMAT_PLUS_FIXTURES));
  fixtures.push(...clone(LITEGEAR_LITEMAT_SPECTRUM_2019_FIXTURES));
  fixtures.push(...clone(LITEGEAR_LITEMAT_S2_FIXTURES));
  fixtures.push(...clone(EVLIGHT_GEM_GEMX_FIXTURES));
  fixtures.push(...clone(EVLIGHT_FRESNEL_FIXTURES));
  fixtures.push(...clone(EVLIGHT_GEMX_HARD_FIXTURES));
  fixtures.push(...clone(EVLIGHT_PROFILE_FIXTURES));
  fixtures.push(...clone(EVLIGHT_GEMX_LARGE_FIXTURES));
  fixtures.push(...clone(KINOFLO_CURRENT_FIXTURES));
  fixtures.push(...clone(KINOFLO_FREESTYLE_AIR_FIXTURES));
  fixtures.push(...clone(KINOFLO_CELEB_LED_FIXTURES));
  fixtures.push(...clone(KINOFLO_DIVA_LITE_LED_FIXTURES));
  fixtures.push(...clone(KINOFLO_IMAGE_SELECT_FIXTURES));
  fixtures.push(...clone(KINOFLO_4BANK_TEGRA_FIXTURES));
  fixtures.push(...clone(KINOFLO_PARABEAM_PARAZIP_FIXTURES));
  fixtures.push(...clone(KINOFLO_VISTABEAM_WALLO_FIXTURES));
  fixtures.push(...clone(KINOFLO_DIVA_BARFLY_FIXTURES));
  fixtures.push(...clone(KINOFLO_IMARA_FIXTURES));
  const kits = [...clone(ARRI_SKYPANEL_KITS), ...clone(ARRI_TUNGSTEN_KITS)];
  const accessoryDefinitions = [...clone(ACCESSORY_LIBRARY), ...clone(ADDITIONAL_ACCESSORY_LIBRARY), ...clone(SPOTLIGHT_ACCESSORY_LIBRARY), ...clone(SPACE_LIGHT_ACCESSORY_LIBRARY), ...clone(STORM_80C_ADAPTED_ACCESSORY_LIBRARY), ...clone(APUTURE_MOUNT_SYSTEM_LIBRARY), ...clone(STORM_SUPPORT_CONTROL_LIBRARY), ...clone(ELECTRO_STORM_TRANSPORT_POWER_LIBRARY), ...clone(ELECTRO_STORM_SYSTEM_ACCESSORY_LIBRARY), ...clone(ARRI_SKYPANEL_X_ACCESSORIES), ...clone(ARRI_SKYPANEL_PRO_ACCESSORIES), ...clone(ARRI_SKYPANEL_CLASSIC_S30_ACCESSORIES), ...clone(ARRI_SKYPANEL_CLASSIC_S60_ACCESSORIES), ...clone(ARRI_SKYPANEL_CLASSIC_S120_ACCESSORIES), ...clone(ARRI_SKYPANEL_CLASSIC_S360_ACCESSORIES), ...clone(ARRI_SKYPANEL_DISCONTINUED_ACCESSORIES), ...clone(ARRI_L_SERIES_PLUS_ACCESSORIES), ...clone(ARRI_ORBITER_ACCESSORIES), ...clone(ARRI_L_SERIES_C_DISCONTINUED_ACCESSORIES), ...clone(ARRI_L_SERIES_DT_TT_DISCONTINUED_ACCESSORIES), ...clone(ARRI_CASTER_SERIES_DISCONTINUED_ACCESSORIES), ...clone(ARRI_M_SERIES_M8_ACCESSORIES), ...clone(ARRI_M_SERIES_M18_ACCESSORIES), ...clone(ARRI_M_SERIES_M40_ACCESSORIES), ...clone(ARRI_M_SERIES_M90_ACCESSORIES), ...clone(ARRI_M_SERIES_ARRIMAX_18_12_ACCESSORIES), ...clone(ARRI_TRUE_BLUE_D5_ACCESSORIES), ...clone(ARRI_TRUE_BLUE_D12_ACCESSORIES), ...clone(ARRI_TRUE_BLUE_D25_ACCESSORIES), ...clone(ARRI_TRUE_BLUE_D40_ACCESSORIES), ...clone(ARRI_DAYLIGHT_18_12_ACCESSORIES), ...clone(ARRI_ARRISUN_DISCONTINUED_ACCESSORIES), ...clone(ARRI_ARRISUN_EVENT_DISCONTINUED_ACCESSORIES), ...clone(ARRI_COMPACT_THEATER_DISCONTINUED_ACCESSORIES), ...clone(ARRI_COMPACT_DISCONTINUED_ACCESSORIES), ...clone(ARRI_ARRILUX_DISCONTINUED_ACCESSORIES), ...clone(ARRI_X_SERIES_DISCONTINUED_ACCESSORIES), ...clone(ARRI_ARRILITE_PLUS_ACCESSORIES), ...clone(ARRI_JUNIOR_ACCESSORIES), ...clone(ARRI_TRUE_BLUE_T1_ACCESSORIES), ...clone(ARRI_TRUE_BLUE_T2_ACCESSORIES), ...clone(ARRI_TRUE_BLUE_T5_ACCESSORIES), ...clone(ARRI_TRUE_BLUE_ST1_ACCESSORIES), ...clone(ARRI_TRUE_BLUE_ST2_3_ACCESSORIES), ...clone(ARRI_TRUE_BLUE_ST5_ACCESSORIES), ...clone(ARRI_TRUE_BLUE_ST_THEATER_ACCESSORIES), ...clone(ARRI_STUDIO_T_ACCESSORIES), ...clone(ARRI_TUNGSTEN_DISCONTINUED_ACCESSORIES)];
  accessoryDefinitions.push(...clone(ASTERA_TITANTUBE_ACCESSORIES));
  accessoryDefinitions.push(...clone(ASTERA_HELIOSTUBE_ACCESSORIES));
  accessoryDefinitions.push(...clone(ASTERA_HYPERIONTUBE_ACCESSORIES));
  accessoryDefinitions.push(...clone(ASTERA_HYDRAPANEL_ACCESSORIES));
  accessoryDefinitions.push(...clone(ASTERA_AX9_POWERPAR_ACCESSORIES));
  accessoryDefinitions.push(...clone(ASTERA_PIXELBRICK_ACCESSORIES));
  accessoryDefinitions.push(...clone(ASTERA_AX5_TRIPLEPAR_ACCESSORIES));
  accessoryDefinitions.push(...clone(ASTERA_AX2_PIXELBAR_ACCESSORIES));
  accessoryDefinitions.push(...clone(ASTERA_NYX_BULB_ACCESSORIES));
  accessoryDefinitions.push(...clone(ASTERA_PLUTOFRESNEL_ACCESSORIES));
  accessoryDefinitions.push(...clone(ASTERA_LEOFRESNEL_ACCESSORIES));
  accessoryDefinitions.push(...clone(ASTERA_QUIKSPOT_ACCESSORIES));
  accessoryDefinitions.push(...clone(ASTERA_LUNABULB_ACCESSORIES));
  accessoryDefinitions.push(...clone(ASTERA_QUIKBEAM_ACCESSORIES));
  accessoryDefinitions.push(...clone(ASTERA_QUIKPUNCH_ACCESSORIES));
  accessoryDefinitions.push(...clone(ASTERA_AX3_LIGHTDROP_ACCESSORIES));
  accessoryDefinitions.push(...clone(ASTERA_SOLABULB_ACCESSORIES));
  accessoryDefinitions.push(...clone(ASTERA_AX1_PIXELTUBE_ACCESSORIES));
  accessoryDefinitions.push(...clone(ASTERA_AX7_SPOTLITE_ACCESSORIES));
  accessoryDefinitions.push(...clone(ASTERA_AX10_SPOTMAX_ACCESSORIES));
  accessoryDefinitions.push(...clone(DESISTI_SUPER_LED_F47_ACCESSORIES));
  accessoryDefinitions.push(...clone(DESISTI_LED_FRESNEL_ACCESSORIES));
  accessoryDefinitions.push(...clone(DESISTI_PICCOLETTO_ACCESSORIES));
  accessoryDefinitions.push(...clone(DESISTI_SOFTLED_ACCESSORIES));
  accessoryDefinitions.push(...clone(DESISTI_GIOTTO_LED_ACCESSORIES));
  accessoryDefinitions.push(...clone(DESISTI_GALILEO_ACCESSORIES));
  accessoryDefinitions.push(...clone(DESISTI_SPACELIGHT_ACCESSORIES));
  accessoryDefinitions.push(...clone(DESISTI_LITE_ACCESSORIES));
  accessoryDefinitions.push(...clone(DESISTI_SOFTLED_VWC_ACCESSORIES));
  accessoryDefinitions.push(...clone(DESISTI_MUSES_ACCESSORIES));
  accessoryDefinitions.push(...clone(DESISTI_TUNGSTEN_ACCESSORIES));
  accessoryDefinitions.push(...clone(DESISTI_TUNGSTEN_SOFT_BROAD_ACCESSORIES));
  accessoryDefinitions.push(...clone(DESISTI_HMI_ACCESSORIES));
  accessoryDefinitions.push(...clone(DESISTI_CONVENTIONAL_EXTRA_ACCESSORIES));
  accessoryDefinitions.push(...clone(GODOX_CONTINUOUS_ACCESSORIES));
  accessoryDefinitions.push(...clone(ALADDIN_MOSAIC_ACCESSORIES));
  accessoryDefinitions.push(...clone(ALADDIN_FABRIC_LITE_ACCESSORIES));
  accessoryDefinitions.push(...clone(ALADDIN_BI_FLEX_ACCESSORIES));
  accessoryDefinitions.push(...clone(ALADDIN_ALL_IN_ACCESSORIES));
  accessoryDefinitions.push(...clone(ALADDIN_BASE_LITE_ACCESSORIES));
  accessoryDefinitions.push(...clone(ALADDIN_ONBOARD_ACCESSORIES));
  accessoryDefinitions.push(...clone(ALADDIN_BI_FABRIC_ACCESSORIES));
  accessoryDefinitions.push(...clone(LITEGEAR_LITEMAT_SPECTRUM_G2_ACCESSORIES));
  accessoryDefinitions.push(...clone(LITEGEAR_LITEMAT_PLUS_ACCESSORIES));
  accessoryDefinitions.push(...clone(LITEGEAR_LITEMAT_SPECTRUM_2019_ACCESSORIES));
  accessoryDefinitions.push(...clone(LITEGEAR_LITEMAT_S2_ACCESSORIES));
  accessoryDefinitions.push(...clone(EVLIGHT_GEM_GEMX_ACCESSORIES));
  accessoryDefinitions.push(...clone(EVLIGHT_FRESNEL_ACCESSORIES));
  accessoryDefinitions.push(...clone(EVLIGHT_GEMX_HARD_ACCESSORIES));
  accessoryDefinitions.push(...clone(EVLIGHT_PROFILE_ACCESSORIES));
  accessoryDefinitions.push(...clone(EVLIGHT_GEMX_LARGE_ACCESSORIES));
  accessoryDefinitions.push(...clone(KINOFLO_CURRENT_ACCESSORIES));
  accessoryDefinitions.push(...clone(KINOFLO_FREESTYLE_AIR_ACCESSORIES));
  accessoryDefinitions.push(...clone(KINOFLO_CELEB_LED_ACCESSORIES));
  accessoryDefinitions.push(...clone(KINOFLO_DIVA_LITE_LED_ACCESSORIES));
  accessoryDefinitions.push(...clone(KINOFLO_IMAGE_SELECT_ACCESSORIES));
  accessoryDefinitions.push(...clone(KINOFLO_4BANK_TEGRA_ACCESSORIES));
  accessoryDefinitions.push(...clone(KINOFLO_PARABEAM_PARAZIP_ACCESSORIES));
  accessoryDefinitions.push(...clone(KINOFLO_VISTABEAM_WALLO_ACCESSORIES));
  accessoryDefinitions.push(...clone(KINOFLO_DIVA_BARFLY_ACCESSORIES));
  accessoryDefinitions.push(...clone(KINOFLO_IMARA_ACCESSORIES));
  const duplicateAccessoryIds = [];
  const accessoriesById = new Map();
  for (const acc of accessoryDefinitions) {
    if (accessoriesById.has(acc.id)) duplicateAccessoryIds.push(acc.id);
    const prev = accessoriesById.get(acc.id);
    accessoriesById.set(acc.id, prev ? mergeAccessory(prev, acc) : clone(acc));
  }
  const accessories = [...accessoriesById.values()];
  const missingAccessoryFixtureIds = [];
  const fixtureIds = new Set(fixtures.map(f => f.id));
  for (const acc of accessories) {
    for (const fixtureId of (acc.compatibleWith || [])) {
      if (!fixtureIds.has(fixtureId)) missingAccessoryFixtureIds.push({ accessoryId: acc.id, fixtureId });
    }
  }
  return {
    fixtures,
    accessories,
    kits,
    integrity: {
      duplicateAccessoryIds: unique(duplicateAccessoryIds),
      missingAccessoryFixtureIds
    }
  };
}
