export const FIXTURE_LIBRARY = [
  {
    id: 'aputure-ls-60d',
    manufacturer: 'Aputure',
    model: 'LS 60d',
    category: 'Light',
    sourceType: 'Daylight LED Focusable',
    powerDrawW: 90,
    outputPowerW: 60,
    cctK: { min: 5600, max: 5600 },
    colorMode: 'Daylight',
    cri: 96,
    tlci: 98,
    beamAngleDeg: { min: 15, max: 45 },
    mount: 'LS 60 Mini Mount',
    control: ['On-board', 'Sidus Link'],
    acInput: '19V DC power supply',
    batterySupport: 'Sony NP-F or D-Tap',
    weatherproofing: true,
    weightKg: 1.8
  },
  {
    id: 'aputure-ls-60x',
    manufacturer: 'Aputure',
    model: 'LS 60x',
    category: 'Light',
    sourceType: 'Bi-Color LED Focusable',
    powerDrawW: 90,
    outputPowerW: 60,
    cctK: { min: 2700, max: 6500 },
    colorMode: 'Bi-Color',
    cri: 96,
    tlci: 98,
    beamAngleDeg: { min: 15, max: 45 },
    mount: 'LS 60 Mini Mount',
    control: ['On-board', 'Sidus Link'],
    acInput: '19V DC power supply',
    batterySupport: 'Sony NP-F or D-Tap',
    weatherproofing: true,
    weightKg: 1.8
  },
  {
    id: 'aputure-ls-300x',
    manufacturer: 'Aputure',
    model: 'LS 300x',
    category: 'Light',
    sourceType: 'Bi-Color LED COB',
    powerDrawW: 350,
    cctK: { min: 2700, max: 6500 },
    colorMode: 'Bi-Color',
    cri: 96,
    tlci: 96,
    mount: 'Bowens',
    control: ['On-board', 'Sidus Link', '2.4GHz'],
    acInput: '100-240V AC, 50/60Hz',
    batterySupport: '12-16.8V batteries'
  },
  {
    id: 'aputure-ls-600d-pro',
    manufacturer: 'Aputure',
    model: 'LS 600d Pro',
    category: 'Light',
    sourceType: 'Daylight LED COB',
    powerDrawW: 720,
    outputPowerW: 600,
    cctK: { min: 5600, max: 5600, tolerance: 200 },
    colorMode: 'Daylight',
    cri: 96,
    tlci: 96,
    mount: 'Bowens',
    dimming: { minPercent: 0, maxPercent: 100 },
    control: ['On-board', 'Sidus Link', 'DMX512', 'Art-Net', 'LumenRadio CRMX'],
    acInput: '100-240V AC, 50/60Hz',
    batterySupport: '48V DC / dual battery operation',
    ipRating: 'IP54'
  },
  {
    id: 'aputure-ls-600x-pro',
    manufacturer: 'Aputure',
    model: 'LS 600x Pro',
    category: 'Light',
    sourceType: 'Bi-Color LED COB',
    powerDrawW: 720,
    outputPowerW: 600,
    cctK: { min: 2700, max: 6500 },
    colorMode: 'Bi-Color',
    cri: 96,
    tlci: 98,
    mount: 'Bowens',
    control: ['On-board', 'Sidus Link', 'DMX512', 'Art-Net', 'LumenRadio'],
    acInput: '100-240V AC, 50/60Hz',
    batterySupport: 'Dual V-Mount or Gold Mount / 48V XLR',
    weatherproofing: 'Dust and water resistant',
    weightKg: 5.16
  },
  {
    id: 'aputure-ls-1200d-pro',
    manufacturer: 'Aputure',
    model: 'LS 1200d Pro',
    category: 'Light',
    sourceType: 'Daylight LED COB',
    powerDrawW: 1440,
    outputPowerW: 1200,
    cctK: { min: 5600, max: 5600 },
    colorMode: 'Daylight',
    cri: 96,
    tlci: 98,
    beamAngleDeg: 66,
    mount: 'Bowens',
    dimming: { minPercent: 0, maxPercent: 100 },
    acInput: '100-240V AC, 50/60Hz',
    batterySupport: '48V XLR, one input half output / two inputs full output',
    lumens: 126413,
    flickerFreeFps: 2000
  },
  {
    id: 'aputure-storm-1200x',
    manufacturer: 'Aputure',
    model: 'STORM 1200x',
    category: 'Light',
    sourceType: 'BLAIR Full-Spectrum LED',
    powerDrawW: 1550,
    outputPowerW: 1200,
    cctK: { min: 2500, max: 10000 },
    colorMode: 'Full Spectrum',
    cri: 95,
    tlci: 95,
    ssi: { tungsten: 87, daylight: 87 },
    beamAngleDeg: 67,
    includedReflectorBeamAngleDeg: 45,
    mount: 'ProLock Bowens Mount',
    greenMagentaAdjustment: '±G 100% (Full ASC MITC Range)',
    control: ['On-board', 'Sidus Link', 'Sidus Link Pro', 'DMX/RDM', 'CRMX', 'sACN', 'Art-Net'],
    acInput: '100-240V AC, 50/60Hz',
    ipRating: 'IP65',
    weightKg: 9.8
  },
  {
    id: 'aputure-storm-1000c',
    manufacturer: 'Aputure',
    model: 'STORM 1000c',
    category: 'Light',
    sourceType: 'BLAIR-CG Full-Color LED',
    powerDrawW: 1440,
    outputPowerW: 1000,
    cctK: { min: 1800, max: 20000 },
    colorMode: 'Full Color',
    colorGamut: '90%+ Rec.2020',
    cri: 97,
    tlci: 97,
    ssi: { tungsten: 88, daylight: 86 },
    beamAngleDeg: 67,
    includedReflectorBeamAngleDeg: 45,
    mount: 'ProLock Bowens Mount',
    greenMagentaAdjustment: '±G 100% (Full ASC MITC Range)',
    control: ['On-board', 'Sidus Link', 'Sidus Link Pro', 'DMX/RDM', 'CRMX', 'sACN', 'Art-Net'],
    acInput: '100-240V AC, 50/60Hz',
    ipRating: 'IP65',
    weightKg: 9.66,
    sourceUrl: 'https://aputure.com/en-US/products/storm-1000c'
  },
  {
    id: 'aputure-ls-600c-pro-ii',
    manufacturer: 'Aputure',
    model: 'LS 600c Pro II',
    category: 'Light',
    sourceType: 'Full-Color LED COB',
    powerDrawW: 720,
    outputPowerW: 600,
    cctK: { min: 2300, max: 10000 },
    colorMode: 'Full Color',
    cri: 95,
    tlci: 98,
    beamAngleDeg: { min: 67, max: 67 },
    includedReflectorBeamAngleDeg: 45,
    mount: 'ProLock Bowens Mount',
    control: ['On-board', 'Sidus Link', 'DMX/RDM', 'CRMX', 'etherCON'],
    acInput: '100-240V AC, 50-60Hz',
    batterySupport: '12-33.6V via two batteries; 48V DC / 15A',
    ipRating: 'IP54',
    weightKg: 5.9,
    sourceUrl: 'https://aputure.com/en-US/products/ls-600c-pro-ii'
  },
  {
    id: 'aputure-ls-300d-ii',
    manufacturer: 'Aputure',
    model: 'LS 300d II',
    category: 'Light',
    sourceType: 'Daylight LED COB',
    powerDrawW: 350,
    outputPowerW: 300,
    cctK: { min: 5600, max: 5600, tolerance: 200 },
    colorMode: 'Daylight',
    cri: 96,
    tlci: 96,
    includedReflectorBeamAngleDeg: 55,
    mount: 'Bowens Mount',
    control: ['On-board', 'Sidus Link', 'DMX512', '2.4GHz Remote'],
    acInput: '100-240V AC, 50/60Hz',
    batterySupport: '12-16.8V battery, 14.4V/14.8V at 15A or higher',
    weightKg: 3.2,
    sourceUrl: 'https://aputure.com/en-US/products/ls-300d-ii'
  },
  {
    id: 'arri-orbiter',
    manufacturer: 'ARRI',
    model: 'Orbiter',
    category: 'Light',
    sourceType: 'Six-color LED spotlight',
    powerDrawW: 500,
    outputPowerW: 400,
    cctK: { min: 2000, max: 20000 },
    colorMode: 'Full Color',
    cri: 98,
    tlci: 95,
    beamAngleDeg: { min: 0, max: 80 },
    mount: '28 mm Spigot (Junior Pin)',
    control: ['On-board', 'LumenRadio CRMX', 'DMX/RDM', 'EtherCON'],
    acInput: '100-240V AC, 50-60Hz',
    batterySupport: '48-52V DC via 3-pin XLR',
    ipRating: 'IP20 without Rain Cover; IP24 with Rain Cover',
    weightKg: 11.7,
    sourceUrl: 'https://www.arri.com/en/lighting/led-spotlights/orbiter/tech-specs'
  },
];
