export const FIXTURE_LIBRARY = [
  { id:'aputure-ls-60d', manufacturer:'Aputure', model:'LS 60d', category:'Light', sourceType:'Daylight LED Focusable', powerDrawW:90, outputPowerW:60, cctK:{min:5600,max:5600}, colorMode:'Daylight', cri:96, tlci:98, beamAngleDeg:{min:15,max:45}, mount:'LS 60 Mini Mount', control:['On-board','Sidus Link'], acInput:'19V DC power supply', batterySupport:'Sony NP-F or D-Tap', weatherproofing:true, weightKg:1.8, sourceUrl:'https://aputure.com/EN-US/products/ls-60d', sourceTypeLabel:'Official Aputure product page' },
  { id:'aputure-ls-60x', manufacturer:'Aputure', model:'LS 60x', category:'Light', sourceType:'Bi-Color LED Focusable', powerDrawW:90, outputPowerW:60, cctK:{min:2700,max:6500}, colorMode:'Bi-Color', cri:96, tlci:98, beamAngleDeg:{min:15,max:45}, mount:'LS 60 Mini Mount', control:['On-board','Sidus Link'], acInput:'19V DC power supply', batterySupport:'Sony NP-F or D-Tap', weatherproofing:true, weightKg:1.8, sourceUrl:'https://aputure.com/en-US/products/ls-60x', sourceTypeLabel:'Official Aputure product page' },
  { id:'aputure-ls-300d-ii', manufacturer:'Aputure', model:'LS 300d II', category:'Light', sourceType:'Daylight LED COB', powerDrawW:350, outputPowerW:300, cctK:{min:5600,max:5600,tolerance:200}, colorMode:'Daylight', cri:96, tlci:96, beamAngleDeg:55, mount:'Bowens', control:['On-board','Sidus Link','DMX512','2.4GHz'], acInput:'100-240V AC, 50/60Hz', batterySupport:'12-16.8V, 15A', weightKg:3.2, sourceUrl:'https://aputure.com/en-US/products/ls-300d-ii', sourceTypeLabel:'Official Aputure product page' },
  { id:'aputure-ls-300x', manufacturer:'Aputure', model:'LS 300x', category:'Light', sourceType:'Bi-Color LED COB', powerDrawW:350, outputPowerW:350, cctK:{min:2700,max:6500}, colorMode:'Bi-Color', cri:96, tlci:96, beamAngleDeg:55, mount:'Bowens', dimming:{minPercent:0,maxPercent:100}, control:['On-board','Sidus Link','DMX512','2.4GHz'], acInput:'100-240V AC, 50/60Hz', batterySupport:'Dual 14.4V/26V batteries', sourceUrl:'https://aputure.com/en-US/products/ls-300x', sourceTypeLabel:'Official Aputure product page' },
  { id:'aputure-ls-600d', manufacturer:'Aputure', model:'LS 600d', category:'Light', sourceType:'Daylight LED COB', powerDrawW:720, outputPowerW:600, cctK:{min:5600,max:5600,tolerance:200}, colorMode:'Daylight', cri:96, tlci:96, beamAngleDeg:105, mount:'Bowens', dimming:{minPercent:0,maxPercent:100}, control:['On-board','Sidus Link','2.4GHz'], acInput:'100-240V AC, 50/60Hz', batterySupport:'Dual 14.4V/26V/28.8V batteries or 48V XLR', weatherproofing:false, lumens:62187, flickerFreeFps:2000, sourceUrl:'https://aputure.com/en-US/products/ls-600d', sourceTypeLabel:'Official Aputure product page' },
  { id:'aputure-ls-600d-pro', manufacturer:'Aputure', model:'LS 600d Pro', category:'Light', sourceType:'Daylight LED COB', powerDrawW:720, outputPowerW:600, cctK:{min:5600,max:5600,tolerance:200}, colorMode:'Daylight', cri:96, tlci:96, mount:'Bowens', dimming:{minPercent:0,maxPercent:100}, control:['On-board','Sidus Link','DMX512','Art-Net','sACN','LumenRadio CRMX'], acInput:'100-240V AC, 50/60Hz', batterySupport:'14.4V/26V/28.8V V-Mount or Gold Mount / 48V XLR', weatherproofing:true, sourceUrl:'https://aputure.com/EN-US/products/ls-600d-pro', sourceTypeLabel:'Official Aputure product page' },
  { id:'aputure-ls-600c-pro-ii', manufacturer:'Aputure', model:'LS 600c Pro II', category:'Light', sourceType:'Full-Color LED COB', powerDrawW:720, outputPowerW:600, cctK:{min:2300,max:10000}, colorMode:'Full Color', cri:95, tlci:98, beamAngleDeg:45, mount:'Bowens', dimming:{minPercent:0,maxPercent:100}, control:['On-board','Sidus Link','DMX/RDM','CRMX','Art-Net','sACN','etherCON'], acInput:'100-240V AC, 50/60Hz', batterySupport:'14.4V/26V/28.8V batteries or 48V XLR', ipRating:'IP54', weightKg:5.9, sourceUrl:'https://aputure.com/en-US/products/ls-600c-pro-ii', sourceTypeLabel:'Official Aputure product page' },
  { id:'aputure-ls-600x-pro', manufacturer:'Aputure', model:'LS 600x Pro', category:'Light', sourceType:'Bi-Color LED COB', powerDrawW:720, outputPowerW:600, cctK:{min:2700,max:6500}, colorMode:'Bi-Color', cri:96, tlci:98, mount:'Bowens', dimming:{minPercent:0,maxPercent:100}, control:['On-board','Sidus Link','DMX512','Art-Net','sACN','LumenRadio CRMX'], acInput:'100-240V AC, 50/60Hz', batterySupport:'Dual 14.4V/26V/28.8V V-Mount or Gold Mount / 48V XLR', weatherproofing:'Dust and water resistant', weightKg:5.16, sourceUrl:'https://aputure.com/en-US/products/ls-600x-pro', sourceTypeLabel:'Official Aputure product page' },
  { id:'aputure-ls-1200d-pro', manufacturer:'Aputure', model:'LS 1200d Pro', category:'Light', sourceType:'Daylight LED COB', powerDrawW:1440, outputPowerW:1200, cctK:{min:5600,max:5600}, colorMode:'Daylight', cri:96, tlci:98, beamAngleDeg:66, reflectorBeamAnglesDeg:[15,30,45], mount:'Bowens', dimming:{minPercent:0,maxPercent:100}, control:['On-board','Sidus Link','DMX512','Art-Net','sACN','LumenRadio CRMX'], acInput:'100-240V AC, 50/60Hz', batterySupport:'2x regulated 48V/15A XLR; one input half output, two inputs full output', ipRating:'IP54', lumens:126413, flickerFreeFps:2000, weightKg:8.95, sourceUrl:'https://aputure.com/en-US/products/ls-1200d-pro', sourceTypeLabel:'Official Aputure product page' },
  { id:'aputure-storm-80c', manufacturer:'Aputure', model:'STORM 80c', category:'Light', sourceType:'BLAIR-CG Full-Spectrum LED', powerDrawW:100, outputPowerW:80, cctK:{min:1800,max:20000}, colorMode:'Full Spectrum', cri:97, tlci:99, beamAngleDeg:60, includedReflectorBeamAngleDeg:35, mount:'Mini ProLock Bowens', control:['On-board','Sidus Link','Sidus Link Pro','DMX/RDM','CRMX'], acInput:'100-240V AC, 50/60Hz', batterySupport:'11-19V DC via handheld bracket/D-Tap or 100W USB-C', ipRating:'IP65', weightKg:1.35, sourceUrl:'https://aputure.com/en-US/products/storm-80c', sourceTypeLabel:'Official Aputure product page' },
  { id:'aputure-storm-400x', manufacturer:'Aputure', model:'STORM 400x', category:'Light', sourceType:'BLAIR Full-Spectrum LED', powerDrawW:500, outputPowerW:400, cctK:{min:2500,max:10000}, colorMode:'Full Spectrum Tunable White', cri:95, tlci:95, beamAngleDeg:57, includedReflectorBeamAngleDeg:35, mount:'ProLock Bowens', control:['On-board','Sidus Link','Sidus Link Pro','DMX/RDM','CRMX'], acInput:'100-240V AC, 50/60Hz', batterySupport:'14.4V V-Mount or Gold Mount', ipRating:'IP65', weightKg:3.95, sourceUrl:'https://aputure.com/en-US/products/storm-400x', sourceTypeLabel:'Official Aputure product page' },
  { id:'aputure-storm-700x', manufacturer:'Aputure', model:'STORM 700x', category:'Light', sourceType:'BLAIR Full-Spectrum LED', powerDrawW:880, outputPowerW:700, cctK:{min:2500,max:10000}, colorMode:'Full Spectrum Tunable White', cri:95, tlci:95, beamAngleDeg:58, includedReflectorBeamAngleDeg:35, mount:'ProLock Bowens', control:['On-board','Sidus Link','Sidus Link Pro','DMX/RDM','CRMX'], acInput:'100-240V AC, 50/60Hz', ipRating:'IP65', weightKg:5.15, sourceUrl:'https://aputure.com/en-US/products/storm-700x', sourceTypeLabel:'Official Aputure product page' },
  { id:'aputure-storm-1000c', manufacturer:'Aputure', model:'STORM 1000c', category:'Light', sourceType:'BLAIR-CG Full-Spectrum LED', powerDrawW:1200, outputPowerW:1000, cctK:{min:1800,max:20000}, colorMode:'Full Spectrum', cri:95, tlci:98, includedReflectorBeamAngleDeg:45, mount:'ProLock Bowens', control:['On-board','Sidus Link','Sidus Link Pro','DMX/RDM','CRMX','sACN','Art-Net'], acInput:'100-240V AC, 50/60Hz', ipRating:'IP65', sourceUrl:'https://aputure.com/en-US/products/storm-1000c', sourceTypeLabel:'Official Aputure product page' },
  { id:'aputure-storm-1200x', manufacturer:'Aputure', model:'STORM 1200x', category:'Light', sourceType:'BLAIR Full-Spectrum LED', powerDrawW:1550, outputPowerW:1200, cctK:{min:2500,max:10000}, colorMode:'Full Spectrum', cri:95, tlci:95, beamAngleDeg:67, includedReflectorBeamAngleDeg:45, mount:'ProLock Bowens', control:['On-board','Sidus Link','Sidus Link Pro','DMX/RDM','CRMX','sACN','Art-Net'], acInput:'100-240V AC, 50/60Hz', ipRating:'IP65', weightKg:9.5, sourceUrl:'https://aputure.com/EN-US/products/storm-1200x', sourceTypeLabel:'Official Aputure product page' }
];
