package com.lightingai.app;
import android.annotation.SuppressLint;import android.bluetooth.*;import android.content.Context;import android.os.*;import org.json.JSONObject;
@SuppressLint("MissingPermission")
public final class AsteraBtbColorReplayProbe {
 public interface Callback{void onComplete(JSONObject r);void onError(JSONObject r,String c);}
 private final Context context;private final Handler handler=new Handler(Looper.getMainLooper());private final Object lock=new Object();private BluetoothGatt activeGatt;private Runnable timeoutRunnable,fallbackSuccessRunnable;private Callback callback;private JSONObject activeResult;private int epoch=0;
 public AsteraBtbColorReplayProbe(Context c){context=c.getApplicationContext();}
 public void replay(String address,String presetValue,int timeoutMs,Callback cb){final String target=address==null?"":address.trim();final AsteraBtbCapturedFrames.Preset preset;try{preset=AsteraBtbCapturedFrames.parsePreset(presetValue);}catch(Exception e){JSONObject r=base(target,presetValue);deliverError(cb,r,"astera_capture_preset_invalid");return;}synchronized(lock){cancelLocked();final int e=++epoch;callback=cb;activeResult=base(target,preset.name());put("captureRevision",AsteraBtbCapturedFrames.CAPTURE_REVISION);put("serviceUuid",AsteraBtbCapturedFrames.SERVICE_UUID.toString());put("characteristicUuid",AsteraBtbCapturedFrames.WRITE_UUID.toString());put("writeType","WRITE_WITHOUT_RESPONSE");put("protocolGeneralized",false);if(!BluetoothAdapter.checkBluetoothAddress(target)){finishError("ble_gatt_bad_address");return;}BluetoothManager m=(BluetoothManager)context.getSystemService(Context.BLUETOOTH_SERVICE);BluetoothAdapter a=m==null?null:m.getAdapter();if(a==null){finishError("bluetooth_unavailable");return;}if(!a.isEnabled()){finishError("bluetooth_disabled");return;}final BluetoothDevice d;try{d=a.getRemoteDevice(target);String n=d.getName();put("deviceName",n==null?"":n);put("bondState",d.getBondState());}catch(SecurityException x){finishError("ble_permission_denied");return;}catch(Exception x){finishError("ble_gatt_bad_address");return;}int t=Math.max(4000,Math.min(12000,timeoutMs));put("timeoutMs",t);timeoutRunnable=()->{synchronized(lock){if(e==epoch&&callback!=null)finishError("astera_capture_timeout");}};handler.postDelayed(timeoutRunnable,t);BluetoothGattCallback gcb=new BluetoothGattCallback(){@Override public void onConnectionStateChange(BluetoothGatt g,int s,int ns){synchronized(lock){if(e!=epoch||g!=activeGatt||callback==null)return;put("connectionStatus",s);put("connectionState",ns);if(s!=BluetoothGatt.GATT_SUCCESS){finishError("astera_capture_connect_status_"+s);return;}if(ns==BluetoothProfile.STATE_CONNECTED){boolean ok;try{ok=g.discoverServices();}catch(Exception x){ok=false;}if(!ok)finishError("astera_capture_service_discovery_start_failed");}else if(ns==BluetoothProfile.STATE_DISCONNECTED)finishError("astera_capture_disconnected");}}
 @Override public void onServicesDiscovered(BluetoothGatt g,int s){synchronized(lock){if(e!=epoch||g!=activeGatt||callback==null)return;put("serviceDiscoveryStatus",s);if(s!=BluetoothGatt.GATT_SUCCESS){finishError("astera_capture_service_discovery_status_"+s);return;}BluetoothGattService svc=g.getService(AsteraBtbCapturedFrames.SERVICE_UUID);if(svc==null){finishError("astera_capture_service_missing");return;}BluetoothGattCharacteristic ch=svc.getCharacteristic(AsteraBtbCapturedFrames.WRITE_UUID);if(ch==null){finishError("astera_capture_characteristic_missing");return;}int props=ch.getProperties();if((props&BluetoothGattCharacteristic.PROPERTY_WRITE_NO_RESPONSE)==0){finishError("astera_capture_characteristic_not_write_nr");return;}byte[] frame=AsteraBtbCapturedFrames.frameFor(preset);if(!AsteraBtbCapturedFrames.isValidFrame(frame)){finishError("astera_capture_frame_crc_invalid");return;}put("preset",preset.name());put("frame",AsteraBtbCapturedFrames.hexFor(preset));int[] rgb=AsteraBtbCapturedFrames.capturedRgb(preset);put("capturedRed",rgb[0]);put("capturedGreen",rgb[1]);put("capturedBlue",rgb[2]);put("characteristicProperties",props);boolean ok;int st=0;try{if(Build.VERSION.SDK_INT>=Build.VERSION_CODES.TIRAMISU){st=g.writeCharacteristic(ch,frame,BluetoothGattCharacteristic.WRITE_TYPE_NO_RESPONSE);ok=st==0;}else{ch.setWriteType(BluetoothGattCharacteristic.WRITE_TYPE_NO_RESPONSE);ch.setValue(frame);ok=g.writeCharacteristic(ch);st=ok?0:-1;}}catch(SecurityException x){finishError("ble_permission_denied");return;}catch(Exception x){finishError("astera_capture_write_exception");return;}put("writeStartStatus",st);put("writeStarted",ok);if(!ok){finishError("astera_capture_write_start_failed_"+st);return;}fallbackSuccessRunnable=()->{synchronized(lock){if(e==epoch&&callback!=null){put("writeCallbackObserved",false);finishSuccess();}}};handler.postDelayed(fallbackSuccessRunnable,800);}}
 @Override public void onCharacteristicWrite(BluetoothGatt g,BluetoothGattCharacteristic ch,int s){synchronized(lock){if(e!=epoch||g!=activeGatt||callback==null||ch==null||!AsteraBtbCapturedFrames.WRITE_UUID.equals(ch.getUuid()))return;if(fallbackSuccessRunnable!=null){handler.removeCallbacks(fallbackSuccessRunnable);fallbackSuccessRunnable=null;}put("writeCallbackObserved",true);put("writeCallbackStatus",s);if(s==BluetoothGatt.GATT_SUCCESS)finishSuccess();else finishError("astera_capture_write_status_"+s);}}};try{activeGatt=d.connectGatt(context,false,gcb,BluetoothDevice.TRANSPORT_LE);if(activeGatt==null)finishError("astera_capture_connect_start_failed");}catch(SecurityException x){finishError("ble_permission_denied");}catch(Exception x){finishError("astera_capture_connect_start_failed");}}}
 public void cancel(){synchronized(lock){cancelLocked();epoch++;}}
 private JSONObject base(String a,String p){JSONObject o=new JSONObject();try{o.put("address",a==null?"":a);o.put("preset",p==null?"":p);o.put("kind","LightingAI-Astera-BTB-captured-color-replay");}catch(Exception ignored){}return o;}
 private void put(String k,Object v){try{if(activeResult!=null)activeResult.put(k,v);}catch(Exception ignored){}}
 private void finishSuccess(){Callback c=callback;JSONObject r=copy(activeResult);cleanup();epoch++;if(c!=null)c.onComplete(r);}
 private void finishError(String code){put("error",code);Callback c=callback;JSONObject r=copy(activeResult);cleanup();epoch++;if(c!=null)c.onError(r,code);}
 private void cancelLocked(){cleanup();}
 private void cleanup(){if(timeoutRunnable!=null){handler.removeCallbacks(timeoutRunnable);timeoutRunnable=null;}if(fallbackSuccessRunnable!=null){handler.removeCallbacks(fallbackSuccessRunnable);fallbackSuccessRunnable=null;}BluetoothGatt g=activeGatt;activeGatt=null;if(g!=null){try{g.disconnect();}catch(Exception ignored){}try{g.close();}catch(Exception ignored){}}callback=null;activeResult=null;}
 private static void deliverError(Callback c,JSONObject r,String code){if(c==null)return;try{r.put("error",code);}catch(Exception ignored){}c.onError(r,code);}
 private static JSONObject copy(JSONObject v){try{return v==null?new JSONObject():new JSONObject(v.toString());}catch(Exception e){return new JSONObject();}}
}