package com.lightingai.app;
import static org.junit.Assert.*;import org.junit.Test;
public class AsteraBtbCapturedFramesTest {
 @Test public void exactFrames(){assertEquals("0A107EDF36000000007D63130D000E000CFF406A",AsteraBtbCapturedFrames.hexFor(AsteraBtbCapturedFrames.Preset.RED));assertEquals("0A107EDF36000000007D63130DD30E960CFFBE0F",AsteraBtbCapturedFrames.hexFor(AsteraBtbCapturedFrames.Preset.WHITE));assertEquals("0A107EDF36000000007D63130C010E030DFFC1A7",AsteraBtbCapturedFrames.hexFor(AsteraBtbCapturedFrames.Preset.GREEN));assertEquals("0A107EDF36000000007D63130C070D010EFFB58E",AsteraBtbCapturedFrames.hexFor(AsteraBtbCapturedFrames.Preset.BLUE));for(AsteraBtbCapturedFrames.Preset p:AsteraBtbCapturedFrames.Preset.values())assertTrue(AsteraBtbCapturedFrames.isValidFrame(AsteraBtbCapturedFrames.frameFor(p)));}
 @Test public void rgb(){assertArrayEquals(new int[]{255,0,0},AsteraBtbCapturedFrames.capturedRgb(AsteraBtbCapturedFrames.Preset.RED));assertArrayEquals(new int[]{255,211,150},AsteraBtbCapturedFrames.capturedRgb(AsteraBtbCapturedFrames.Preset.WHITE));assertArrayEquals(new int[]{1,255,3},AsteraBtbCapturedFrames.capturedRgb(AsteraBtbCapturedFrames.Preset.GREEN));assertArrayEquals(new int[]{7,1,255},AsteraBtbCapturedFrames.capturedRgb(AsteraBtbCapturedFrames.Preset.BLUE));}
 @Test(expected=IllegalArgumentException.class) public void failClosed(){AsteraBtbCapturedFrames.frameFor("MAGENTA");}
 @Test public void captureIsRestrictedToObservedFixture(){assertTrue(AsteraBtbCapturedFrames.supportsDeviceName("TITAN 01021450"));assertTrue(AsteraBtbCapturedFrames.supportsDeviceName(" titan 01021450 "));assertFalse(AsteraBtbCapturedFrames.supportsDeviceName("TITAN 99999999"));assertFalse(AsteraBtbCapturedFrames.supportsDeviceName(null));}
 @Test public void corruptionAndWrongEnvelopeAreRejected(){byte[] f=AsteraBtbCapturedFrames.frameFor("RED");f[13]^=1;assertFalse(AsteraBtbCapturedFrames.isValidFrame(f));assertFalse(AsteraBtbCapturedFrames.isValidFrame(null));assertFalse(AsteraBtbCapturedFrames.isValidFrame(new byte[19]));assertFalse(AsteraBtbCapturedFrames.isValidFrame(new byte[21]));}
 @Test public void returnedFrameCannotMutateCapturedBytes(){byte[] f=AsteraBtbCapturedFrames.frameFor("RED");f[0]=0;assertTrue(AsteraBtbCapturedFrames.isValidFrame(AsteraBtbCapturedFrames.frameFor("RED")));}
}
